### ISSUE TITLE
To train an event VAE, the code expects a file of event data. We provide some sample files to train representations over

### ISSUE THREAD

**Issue by wangxiao5791509** [microsoft/event-vae-rl#1]
Hi, thanks for sharing the code. In this Github, I find: "To train an event VAE, the code expects a file of event data. We provide **some sample files** to train representations over,  ... " 

Where to download the sample files?

**Comment by saihv** [comment]
@wangxiao5791509 The sample files are in the releases section - https://github.com/microsoft/event-vae-rl/releases/tag/v1.0-d

I have edited the README to make this clear, thanks for pointing it out!

**Comment by wangxiao5791509** [comment]
thanks for your feedback. @saihv
