### ISSUE TITLE
how to collect data and train vae

### ISSUE THREAD

**Issue by aahuhu** [microsoft/event-vae-rl#5]
Hi,Sai Vemprala.I have tried to reproduce your code in my own environment these days .The eVAE goes well when training,however performances poorly as the obervation in PPO training process.I have tried several methods to collect training data for eVAE but failed.Could you please tell me how you collect training data for the eVAE?

**Comment by saihv** [comment]
@aahuhu Collecting training data for the eVAE is mainly just about flying the drone around in the environment and getting enough event data that captures the kind of scene (e.g. obstacles) that you're interested in. How do the reconstructions look when training the eVAE? On the other hand, you might also want to tune the hyperparameters of the PPO training as well.

**Comment by aahuhu** [comment]
Thank you very much! The whole algorithom works well now, but it needs twice as many episodes as your 500k  in PPO training.  As you said, I need to tune the hyperparameters of the PPO training later.
